import ContactContainer from "../components/containers/ContactContainer";

export const metadata = {
  title: "KINGA FLASZA | Contact",
  description: "Generated by create next app",
};

export default function Bio() {
  return <ContactContainer />;
}
