import BioContainer from "../components/containers/BioContainer";

export const metadata = {
  title: "KINGA FLASZA | Bio",
  description: "Generated by create next app",
};

export default function Bio() {
  return <BioContainer />;
}
