import ExhibitionsContainer from "../components/containers/ExhibitionsContainer";

export const metadata = {
  title: "KINGA FLASZA | Exhibitions",
  description: "Generated by create next app",
};

export default function Exhibitions() {
  return <ExhibitionsContainer />;
}
