import PaintingsContainer from "../components/containers/PaintingsContainer";

export const metadata = {
  title: "KINGA FLASZA | Paintings",
  description: "Generated by create next app",
};

export default function Paintings() {
  return <PaintingsContainer />;
}
