import HomeContainer from "@/app/components/containers/HomeContainer";

export const metadata = {
  title: "KINGA FLASZA | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return <HomeContainer />;
}
